name: 'dbt_project'
version: '1.0.0'
config-version: 2

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_project:
    # Staging models - materialized as views in default dataset (olist_silver)
    staging:
      +materialized: view
      +schema: null  # Uses default dataset from profiles.yml
    
    # Intermediate models - ephemeral 
    intermediate:
      +materialized: ephemeral
    
    # Marts models - tables in gold dataset
    marts:
      +schema: gold

      core:
        fct_orders:
          +materialized: incremental
          +incremental_strategy: merge
        fct_order_items:
          +materialized: incremental
          +incremental_strategy: merge
        dim_customers:
          +materialized: table
        dim_products:
          +materialized: table
        dim_sellers:
          +materialized: table

      analytics:
        +materialized: table
