dbt_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: olist_silver
      location: EU
      keyfile: /usr/app/keys/service_account.json  # Path in Docker container
      threads: 4
      timeout_seconds: 300
      maximum_bytes_billed: 1000000000
      priority: interactive
