# Base Python image
FROM python:3.11-slim

# Install basic dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /usr/app

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install dbt-core dbt-bigquery

# Set environment variable for BigQuery auth
ENV GOOGLE_APPLICATION_CREDENTIALS=/usr/app/keys/service_account.json

# Default command
CMD ["bash"]