version: 2

sources:
  - name: bronze
    database: datawarehouse-479612
    schema: olist_bronze
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: order_payments
      - name: reviews
      - name: products
      - name: sellers
      - name: geolocations
      - name: product_category_name_translation