version: 2

models:
  - name: stg_customers
    description: "Cleaned customer data"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        tests:
          - not_null
          
  - name: stg_orders
    description: "Cleaned order data"
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: order_status
        tests:
          - accepted_values:
              values: ['delivered', 'shipped', 'approved', 'canceled', 'unavailable', 'invoiced', 'processing', 'created']
              
  - name: stg_order_items
    description: "Cleaned order items"
    columns:
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: price
        tests:
          - not_null
          - expression:
              expression: "price >= 0"
      - name: freight_value
        tests:
          - not_null
          - expression:
              expression: "freight_value >= 0"
              
  - name: stg_products
    description: "Cleaned product data"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: product_weight_g
        tests:
          - expression:
              expression: "product_weight_g >= 0 OR product_weight_g IS NULL"
              
  - name: stg_reviews
    description: "Cleaned review data"
    columns:
      - name: review_id
        # Removed unique test - there are duplicates in the data
        tests:
          - not_null
      - name: review_score
        tests:
          - not_null
          - expression:
              expression: "review_score >= 1 AND review_score <= 5"
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id